/**
 * @file Drizzle database schema for Hibiki guild configurations.
 * @author Espi Marisa <contact@espi.me>
 * @license zlib
 */

import { pgTable, text, uuid } from "drizzle-orm/pg-core";

/**
 * Database schema for a valid Hibiki guild configuration object.
 */

export const guildConfig = pgTable("guild_config", {
  /** The guild's unique Discord guild ID. */
  guild_id: text("guild_id").notNull(),

  /** The primary key identifier generated by PostgreSQL. */
  id: uuid("id").defaultRandom().primaryKey(),
});

/**
 * A valid Hibiki guild configuration object.
 */

export type HibikiGuildConfig = typeof guildConfig.$inferSelect;
