/**
 * @file Drizzle database schema for Hibiki user configurations.
 * @author Espi Marisa <contact@espi.me>
 * @license zlib
 */

import { pgTable, text, uuid } from "drizzle-orm/pg-core";

/**
 * Database schema for a valid Hibiki user configuration object.
 */

export const userConfig = pgTable("user_config", {
  /** The primary key identifier generated by PostgreSQL. */
  id: uuid("id").primaryKey().defaultRandom(),

  /** The user's unique Discord user ID. */
  user_id: text("user_id").notNull(),
});

/**
 * A valid Hibiki user configuration object.
 */

export type HibikiUserConfig = typeof userConfig.$inferSelect;
