services:
  hibiki:
    container_name: hibiki
    restart: unless-stopped
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    networks: [hibiki-network]
    volumes:
      - hibiki-data:/usr/src/app

networks:
  hibiki-network:
    driver: bridge
    external: true
    enable_ipv6: false
    name: hibiki-network

volumes:
  hibiki-data:
    external: true
    name: hibiki-data
