/**
 * @file Valid items
 * @description Valid guildconfig and userconfig items
 * @module utils/validItems
 */

export const validItems = [
  {
    category: "features",
    emoji: "☑",
    id: "agreeChannel",
    type: "channelID",
  },
  {
    category: "roles",
    emoji: "✔",
    id: "agreeRole",
    type: "roleID",
  },
  {
    category: "automod",
    emoji: "🔗",
    id: "antiInvite",
    type: "bool",
  },
  {
    category: "automod",
    emoji: "😶",
    id: "antiNewLines",
    type: "bool",
  },
  {
    category: "automod",
    emoji: "🔨",
    id: "antiNewLinesPunishments",
    type: "punishment",
  },
  {
    category: "automod",
    emoji: "#️⃣",
    id: "newlineThreshold",
    type: "number",
    minimum: 10,
  },
  {
    category: "automod",
    emoji: "🚯",
    id: "antiSpam",
    type: "bool",
  },
  {
    id: "assignableRoles",
    type: "roleArray",
  },
  {
    category: "roles",
    emoji: "👤",
    id: "autoRoles",
    type: "roleArray",
    maximum: 5,
  },
  {
    id: "disabledCategories",
    type: "array",
  },
  {
    id: "disabledCmds",
    type: "array",
  },
  {
    category: "features",
    id: "easyTranslate",
    emoji: "🌍",
    type: "bool",
  },
  {
    category: "automod",
    emoji: "⚒",
    id: "invitePunishments",
    type: "punishment",
  },
  {
    category: "logging",
    emoji: "👋",
    id: "leaveJoin",
    type: "channelID",
  },
  {
    category: "logging",
    emoji: "✉",
    id: "joinMessage",
    type: "string",
    minimum: 1,
    maximum: 200,
  },
  {
    category: "logging",
    emoji: "🚪",
    id: "leaveMessage",
    type: "string",
    minimum: 1,
    maximum: 200,
  },
  {
    category: "logging",
    emoji: "📄",
    id: "eventLogging",
    type: "channelID",
  },
  {
    category: "logging",
    emoji: "📜",
    id: "messageLogging",
    type: "channelID",
  },
  {
    category: "logging",
    emoji: "📰",
    id: "memberLogging",
    type: "channelID",
  },
  {
    category: "logging",
    emoji: "📃",
    id: "modLogging",
    type: "channelID",
  },
  {
    category: "logging",
    emoji: "📵",
    id: "ignoredLoggingChannels",
    type: "channelArray",
  },
  {
    category: "automod",
    emoji: "💬",
    id: "msgOnPunishment",
    type: "bool",
  },
  {
    category: "roles",
    emoji: "🔕",
    id: "mutedRole",
    type: "roleID",
  },
  {
    category: "sniping",
    emoji: "💣",
    id: "snipingEnable",
    type: "bool",
  },
  {
    category: "sniping",
    emoji: "🚫",
    id: "snipingIgnore",
    type: "channelArray",
  },
  {
    category: "sniping",
    emoji: "🔗",
    id: "snipingInvites",
    type: "bool",
  },
  {
    category: "sniping",
    emoji: "⛔",
    id: "snipingPermission",
    type: "bool",
  },
  {
    category: "roles",
    emoji: "🔨",
    id: "staffRole",
    type: "roleID",
  },
  {
    category: "pinboard",
    emoji: "🔢",
    id: "pinAmount",
    type: "number",
  },
  {
    category: "pinboard",
    emoji: "📍",
    id: "pinChannel",
    type: "channelID",
  },
  {
    category: "pinboard",
    emoji: "⭐",
    id: "pinEmoji",
    type: "emoji",
  },
  {
    category: "pinboard",
    emoji: "🗣",
    id: "pinSelfPinning",
    type: "bool",
  },
  {
    id: "prefix",
    type: "string",
    minimum: 1,
    maximum: 15,
  },
  {
    category: "automod",
    emoji: "🛠",
    id: "spamPunishments",
    type: "punishment",
  },
  {
    category: "automod",
    emoji: "🔢",
    id: "spamThreshold",
    minimum: 5,
    maximum: 10,
    type: "number",
  },
  {
    category: "roles",
    emoji: "☑",
    id: "verifiedRole",
    type: "roleID",
  },
  {
    emoji: "🏷️",
    category: "profile",
    id: "bio",
    type: "string",
    minimum: 1,
    maximum: 200,
    inviteFilter: true,
  },
  {
    emoji: "💖",
    category: "profile",
    id: "pronouns",
    type: "pronouns",
  },
  {
    emoji: "🕒",
    category: "profile",
    id: "timezone",
    type: "timezone",
  },
  {
    emoji: "🚫",
    category: "profile",
    id: "timezoneHide",
    type: "bool",
  },
];
